#Before modifying this file, ensure the editor is tab intended

#Listing down all the rules, to ensure their execution 
#irrespective of existing file in the Makefile location
.PHONY: deploy test clean default lint docker

EXE?= runme

#if nothing sepcified use this default variable
LIB_DIR?=lib
SRC_DIR?=./src
TEST_DIR?=./test
OBJ_DIR?=./obj
CPP_FLAGS?=-std=c++17 -Wall
C_FLAGS?=-Wall

INCLUDES=-I./\
		-I./include\
		-I$(SRC_DIR)/include\
		-I$(TEST_DIR)/include

CPP_SRCS=$(TEST_DIR)/test_main.cpp
C_SRCS=$(SRC_DIR)/clockp.c
AUTOGEN_SRCS=$(SRC_DIR)/clockp_autogen.c

CPP_OBJS=$(CPP_SRCS:.cpp=.o)

C_OBJS=$(C_SRCS:.c=.o)

AUTOGEN_OBJS=$(AUTOGEN_SRCS:.c=.o)

#The standard structure of Makefile is as below
#TARGET: PREQUISITES
#	RECIPE
#The first rule is default rule. If nothing is specified only this rule is executed
default: $(C_SRCS)
	@echo "1 Building the main application in standalone mode"
	gcc $(C_FLAGS) $(INCLUDES) $(C_SRCS) -DINCLUDE_MAIN -o $(EXE)

test: 
	@echo "1 Generating objects for all c files"
	gcc $(C_FLAGS) $(INCLUDES) -c $(C_SRCS) -o $(C_OBJS)
	@echo "2 Generating objects for unit test framework. This can take about 2 minutes"
	g++ $(CPP_FLAGS) $(INCLUDES) -c $(CPP_SRCS) -o $(CPP_OBJS)
	g++ -o $(EXE) $(C_OBJS) $(CPP_OBJS)

clean:
	@echo "Removing temporary object and autogenerated files"
	rm $(C_OBJS) $(CPP_OBJS) $(EXE) $(AUTOGEN_OBJS) $(AUTOGEN_SRCS)

lint:
	@echo "TODO: Linting the codebase"
	#TODO:
	#oclint $(LINT_SRC) $(CPP_FLAGS) $(INCLUDES)

.PHONY: docker autogen autogen_test
docker:
	@echo "current directory is $(shell pwd)"
	$(shell pwd)
	@docker run -it --rm --name my-env -v "$(shell pwd)":/usr/src/app -w /usr/src/app py3-gxx-make make

autogen:
	@echo "Auto generating the file based on descriptor time_res.json"
	python scripts/generator.py
	gcc $(C_FLAGS) $(INCLUDES) $(AUTOGEN_SRCS) -DINCLUDE_MAIN -o $(EXE)

autogen_test: 
	@echo "1 Generating objects for autogenerated c files"
	gcc $(C_FLAGS) $(INCLUDES) -c $(AUTOGEN_SRCS) -o $(AUTOGEN_OBJS)
	@echo "2 Generating objects for unit test framework. This can take about 2 minutes"
	g++ $(CPP_FLAGS) $(INCLUDES) -c $(CPP_SRCS) -o $(CPP_OBJS)
	g++ -o $(EXE) $(AUTOGEN_OBJS) $(CPP_OBJS)

# TODO: Update the hard coded file names with autofill

#% gcc -c clockp.c -I.
#% g++ -c test_main.cpp  -std=c++17 -I.
#% g++ -o runme test.o clockp.o
#% gcc -Wall -I./ -I./include -I./src/include ./src/clockp.c -o opt

